version: "3.8"
services:

  toy-caching-service:
    image: thedarkside/toy-caching-service:latest
    container_name: toy-caching-service
    ports:
      - 9012:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=password
      # Overwrite settings in application.yaml within the image
      - SPRING_DATA_REDIS_SSL_ENABLED=false
      - SPRING_DATA_REDIS_TIMEOUT=15000

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - 9411:9411

networks:
  default:
    name: local-stack-network
    external: true


